name: twitter_ui
description: A new Flutter project.


publish_to: 'none'



environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.3.0
  flutter_svg: ^1.1.6
  provider: ^6.0.5
  drift: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2
  intl: ^0.17.0
  image_picker: ^0.8.6




dev_dependencies:
  drift_dev: ^2.3.3
  build_runner: ^2.3.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.0.4
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Icons_image/twitter.png"
  min_sdk_android: 21


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - images/
    - Icons_image/


  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

